baseURL = '/'
languageCode = 'zh-tw'
title = 'æ˜Ÿç©ºä¸‹å¾®é¢¨è¼•æ‹‚é»ƒå…‰é–ƒè€€çš„ä¸–ç•Œä¸‰'
theme = 'stack'
[params.sidebar]
emoji = "ğŸ¢"
subtitle = "2025å¹´è‡³2038å¹´ç´€éŒ„ä¸‰"
[params.sidebar.avatar]
enabled = true
local = true
src = "/img/avatar.png"
[deployment]
  [[deployment.targets]]
    name = 'production'
    url = 's3://fenghuanghsin?region=ap-southeast-2'
